// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0sPIkF8lM-q4NpEplCvWYKUsgWe5KKnI',
    appId: '1:686942291745:web:048e87ef83aa489dd52060',
    messagingSenderId: '686942291745',
    projectId: 'financetracker-b215b',
    authDomain: 'financetracker-b215b.firebaseapp.com',
    databaseURL: 'https://financetracker-b215b-default-rtdb.firebaseio.com',
    storageBucket: 'financetracker-b215b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpjokpD1B0wh8AQyWA0utEm1koNtqzbc',
    appId: '1:686942291745:android:0c424985f75fe668d52060',
    messagingSenderId: '686942291745',
    projectId: 'financetracker-b215b',
    databaseURL: 'https://financetracker-b215b-default-rtdb.firebaseio.com',
    storageBucket: 'financetracker-b215b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0H7RAa6WeKvRRPPbf21qyTRBGniFbsc',
    appId: '1:686942291745:ios:761c82812139fcc0d52060',
    messagingSenderId: '686942291745',
    projectId: 'financetracker-b215b',
    databaseURL: 'https://financetracker-b215b-default-rtdb.firebaseio.com',
    storageBucket: 'financetracker-b215b.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0H7RAa6WeKvRRPPbf21qyTRBGniFbsc',
    appId: '1:686942291745:ios:761c82812139fcc0d52060',
    messagingSenderId: '686942291745',
    projectId: 'financetracker-b215b',
    databaseURL: 'https://financetracker-b215b-default-rtdb.firebaseio.com',
    storageBucket: 'financetracker-b215b.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0sPIkF8lM-q4NpEplCvWYKUsgWe5KKnI',
    appId: '1:686942291745:web:ed76b189da06039fd52060',
    messagingSenderId: '686942291745',
    projectId: 'financetracker-b215b',
    authDomain: 'financetracker-b215b.firebaseapp.com',
    databaseURL: 'https://financetracker-b215b-default-rtdb.firebaseio.com',
    storageBucket: 'financetracker-b215b.firebasestorage.app',
  );
}
